[package]
name = "one-sql"
version = "0.1.0"
description = "One SQL agent"
edition = "2021"

[[bin]]
name = "agent"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
axum = "0.7.4"
clap = { version = "4.4.18", features = ["derive"] }
hex = "0.4.3"
lazy_static = "1.4.0"
lru = "0.12.1"
rand = "0.8.5"
regex = "1.10.3"
rust-ini = "0.20.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
uuid = { version = "1.7.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.9.0"
