[package]
name = "one-sql"
version = "0.1.0"
description = "One SQL agent"
edition = "2021"
build = "src/build.rs"

[[bin]]
name = "agent"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
axum = { version="0.7.4", features = ["macros", "tracing"] }
clap = { version = "4.4.18", features = ["derive"] }
hex = "0.4.3"
lazy_static = "1.4.0"
lru = "0.12.1"
rand = "0.8.5"
regex = "1.10.3"
rust-ini = "0.20.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
sysinfo = "0.30.5"
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
tower-http = { version = "0.5.1",  features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.7.0", features = ["v4"] }
reqwest = "0.11.24"

[dev-dependencies]
nix = { version = "0.27.1", features = ["signal", "process"] }
tempfile = "3.9.0"
tower = "0.4.13"

[build-dependencies]
built = { version = "0.7.1", features = ["git2"] }
